program: src/train.py
method: grid
metric:
  name: val_loss
  goal: minimize
command:
  - ${env}
  - python
  - ${program}
  - model=consistency_model
  - ${args}
parameters:
  model.lr:
    values: [1e-4, 5e-4, 1e-5]
  model.ema_rate:
    values: [0.90, 0.95, 0.99]
  model.num_steps:
    values: [5, 10, 20, 40]
  model.sigma_min:
    values: [0.002, 0.01]
  model.sigma_max:
    values: [5.0, 10.0, 20.0, 40.0]
